### PR TITLE
Feature/2733 189 upgrate to mui v5

### LINKED ISSUE #189: Upgrade to using MUI v5
#### Describe the desired behavior
Update library to use the latest MUI v5 (@mui/material)
#### Describe the current behavior
We are using the old version 4.x
#### Is this request related to a current issue?
No

### PR DESCRIPTION
**Pull request by bkarambe**
Fixes #189 

#### Changes proposed in this Pull Request:
- Upgraded material ui to v5

#### To Test:
- yarn start

### CODE REVIEW

**Comment by emclaug2** [comment]
@bkarambe Can you commit a new `yarn.lock` file?

**Comment by ektasawant** [comment]
1.
Dev branch : Padding 12px
Screenshot 2022-04-05 at 10 10 16 AM
MUIV5 branch : Padding 8px
Screenshot 2022-04-05 at 10 10 31 AM

2.
Dev branch
Screenshot 2022-04-05 at 10 12 59 AM
MUIV5 branch
Screenshot 2022-04-05 at 10 12 52 AM

3.
MUIV5 branch: hamburger should be align with checkbox (padding 8 issue)
Screenshot 2022-04-05 at 10 17 54 AM

4.
Dev branch
Screenshot 2022-04-05 at 10 19 49 AM
MUIV5 branch: search input styling not matching
Screenshot 2022-04-05 at 10 19 55 AM

5.
MUIV5 branch: padding should remove
Screenshot 2022-04-05 at 10 20 55 AM

6.
MUIV5 branch: mobile view breaking
Screenshot 2022-04-05 at 10 24 04 AM

7.
Dev branch: snackbar is at bottom center
Screenshot 2022-04-05 at 10 29 21 AM

MUIV5 branch: snackbar is not at bottom center, input style is not matching dev branch's styling.
Screenshot 2022-04-05 at 10 29 43 AM

8.
Dev branch: button style in progress bar (http://localhost:3000/progress-bar)
Screenshot 2022-04-05 at 10 39 43 AM
MUIV5 branch:  button style in progress bare is not matching dev branch's styling.
Screenshot 2022-04-05 at 10 39 34 AM

**Comment by jeffvg** [comment]
I'm still looking at the cypress dependencies and failing tests

**Comment by jeffvg** [comment]
mobile view on responsive table displaying both views

image

**Comment by jeffvg** [comment]
contextual-action list on tablet (dev)
image

contextual-action list on tablet (mui)
image

**Comment by jeffvg** [comment]
dynamic stepper (dev)
image

dynamic stepper (mui) plus appbar not spanning across
image

**Comment by jeffvg** [comment]
collapsible appbar (dev) with background-image
image

collapsible appbar (mui) without background-image
image

**Comment by ektasawant** [comment]
Changes looks most of the issues have been fixed 👍 .

Few things need to be fixed.
600px to 900px showing delete button which should be hidden.
Screenshot 2022-04-08 at 1 27 57 PM

Divider is breaking in sectioned form design pattern
Screenshot 2022-04-08 at 1 17 46 PM

600px to 900px showing delete button which should be hidden.
Screenshot 2022-04-08 at 1 10 40 PM

Button style is not matching with dev branch's style.
Screenshot 2022-04-08 at 1 20 23 PM

**Comment by jeffvg** [comment]
looks like the i18n example needs styling. Form and snackbar

mui 5 branch
image

dev branch
image

**Review by ektasawant — APPROVED** [review]

**Pull request merged**
