### PR TITLE
Feature/2539 list tree structure

### PR DESCRIPTION
**Pull request by daileytj**
Fixes PXBLUE-2539.

#### Changes proposed in this Pull Request:
- Add list tree structure

### CODE REVIEW

**Comment by ektasawant** [comment]
1. Can we match width of container as per design (i.e. 768px multiple of 8)

2. Color of folder Icon should be `#727E84`.
Screenshot 2021-12-28 at 1 51 49 PM

3. We can remove`New folder` and `Remove` non-functional buttons. Issue for NG design pattern https://github.com/brightlayer-ui/angular-design-patterns/issues/162
Screenshot 2021-12-28 at 1 44 29 PM

4. Background of selected row not as per design.
Screenshot 2021-12-28 at 1 44 19 PM

5. Can we remove border from last row `rgba(0, 123, 193, 0.05)`?

Screenshot 2021-12-28 at 1 54 25 PM

**Comment by daileytj** [comment]
@ektasawant Updates are in, however, I didn't "fix" the bottom border issue as there is no bottom border on the last element; this is just the default elevation on the card. We can alter the elevation if needed.

**Comment by jeffvg** [comment]
looks good, noticed the folder and radio button outline should be #424e54

**Comment by daileytj** [comment]
Good eye @jeffvg, I've updated the selected colors for the radio button and folders. This is ready for a second look.

**Comment by daileytj** [comment]
Thought you were talking about the selected color and didn't even check the hex values you commented. I'm on it

**Comment by daileytj** [comment]
@jeffvg I'm not seeing the same thing you're proposing in the designs. The folder color and radio button should both be gray[500] (#727E84)

**Comment by jeffvg** [comment]
> 

Sorry about the folder color, thought I saw that in the design, but I guess the angular example is incorrect for folder color.
image

@huayunh called out the subtitle2 during the work done on global action items we did. The Angular example is .875 also. I'm good either way

**Review by jeffvg — APPROVED** [review]

**Pull request merged**
